module.exports = [
    {
        school_name: 'golden_west',
        Ho: 'First or Given Name',
        ChuLot: '',
        Ten: 'Middle Name',
        FullName: 'Surname or Family Name as it appears on passport',
        GioiTinh: '',
        NgaySinh: 'Date of Birth ex January 1 1990',
        day: '',
        month: '',
        year: '',
        NoiSinh: 'Province  State',
        QuocTich: '',
        SoNha: 'Students Permanent Address in Home Country REQUIRED',
        ThanhPho: 'City',
        QuocGia: 'Country',
        FullAddress: '',
        SoDienThoai: 'Telephone include country  area codes',
        Email: 'Student Email',
    },
    {
        school_name: 'sanfancisco',
        Ho: 'First Name',
        ChuLot: '',
        Ten: 'Middle Names',
        FullName: 'Family NameSurname',
        GioiTinh: '',
        NgaySinh: 'Date of Birth',
        day: 'undefined',
        month: 'Date of Birth',
        year: 'undefined_2',
        NoiSinh: 'StateProvince',
        QuocTich: '',
        SoNha: 'Address 1',
        ThanhPho: 'City',
        QuocGia: 'Country',
        FullAddress: '',
        SoDienThoai: 'Phone',
        Email: 'Email',
    },
    {
        school_name: 'santiego',
    },
    {
        school_name: 'university_of_science',
        Ho: '',
        ChuLot: '',
        Ten: '',
        FullName: 'Family Name',
        GioiTinh: '',
        NgaySinh: 'Date of Birth',
        day: '',
        month: '',
        year: '',
        NoiSinh: 'Country of birth',
        QuocTich: 'Nationality',
        SoNha: 'Full Address',
        ThanhPho: 'City',
        QuocGia: 'Student Country',
        FullAddress: '',
        SoDienThoai: 'Telephone (home/mobile)',
        Email: 'Student Email',
    },
    {
        school_name: 'barrara',
    }
]